apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: error-pages
  name: error-pages
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: error-pages
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: error-pages
    spec:
      containers:
        - env:
            - name: SHOW_DETAILS
              value: "true"
            - name: TEMPLATE_NAME
              value: lost-in-space
          image: tarampampam/error-pages
          name: error-pages
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
